/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC5192__factory } from "./IERC5192__factory";
export { KavachTrustSBT__factory } from "./KavachTrustSBT__factory";
