services:
  - type: web
    name: kavachtrust-backend
    runtime: node
    rootDir: backend
    buildCommand: pnpm install --frozen-lockfile && pnpm prisma generate && pnpm build
    startCommand: pnpm prisma migrate deploy && pnpm start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_PREFIX
        value: /api/v1
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: MINIO_ACCESS_KEY
        sync: false
      - key: MINIO_SECRET_KEY
        sync: false
      - key: MINIO_ENDPOINT
        value: ''
      - key: MINIO_PORT
        value: 443
      - key: MINIO_USE_SSL
        value: false
      - key: MINIO_BUCKET
        value: kavachtrust-evidence
      - key: BLOCKCHAIN_MODE
        value: demo
      - key: BLOCKCHAIN_PRIVATE_KEY
        sync: false
      - key: BLOCKCHAIN_RPC_URL
        value: ''
      - key: BLOCKCHAIN_CHAIN_ID
        value: ''
      - key: CONTRACT_ADDRESS
        value: ''
