import json
import logging
from pathlib import Path
from web3 import Web3
from web3.exceptions import Web3Exception

logger = logging.getLogger(__name__)

class BlockchainService:
    def __init__(self, rpc_url="http://127.0.0.1:8545"):
        self.w3 = Web3(Web3.HTTPProvider(rpc_url))
        self.contract = None
        self.account = None
        
        # Load ABI if exists
        self.artifact_path = Path(__file__).parent.parent.parent.parent / "contracts" / "artifacts" / "contracts" / "KavachTrustSBT.sol" / "KavachTrustSBT.json"
        
        if self.w3.is_connected():
            logger.info(f"Connected to local blockchain at {rpc_url}")
            # Use the first account generated by Hardhat
            self.account = self.w3.eth.accounts[0] if self.w3.eth.accounts else None
        else:
            logger.warning("Could not connect to local blockchain. Blockchain features will operate in mock mode.")
            
    def _load_contract(self):
        if not self.artifact_path.exists():
            raise FileNotFoundError("Contract artifact not found. Run 'pnpm compile' in contracts/ directory.")
            
        with open(self.artifact_path, 'r') as f:
            artifact = json.load(f)
            
        # If contract address is not saved, we would normally fetch it from a config or env
        # For this demo, let's deploy it dynamically on initialization if it's a local network
        # or load a pre-deployed address. We will deploy it right away if not deployed.
        
        # We will deploy dynamically for ease of use in the prototype
        Contract = self.w3.eth.contract(abi=artifact['abi'], bytecode=artifact['bytecode'])
        tx_hash = Contract.constructor().transact({'from': self.account})
        tx_receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash)
        
        self.contract = self.w3.eth.contract(
            address=tx_receipt.contractAddress,
            abi=artifact['abi']
        )
        logger.info(f"Deployed KavachTrustSBT to {tx_receipt.contractAddress}")

    def get_contract(self):
        if not self.contract and self.w3.is_connected() and self.account:
            try:
                self._load_contract()
            except Exception as e:
                logger.error(f"Failed to load/deploy contract: {e}")
        return self.contract

    def mint_certification(self, to_did: str, asset_id: str, batch_id: str, evidence_hash: str) -> dict:
        """Mint a new certification SBT on-chain."""
        contract = self.get_contract()
        if not contract:
            # Fallback mock for when blockchain is not running
            return {
                "tx_hash": "0xmock" + evidence_hash[:40],
                "token_id": 999,
                "block_number": 1,
                "gas_used": 21000
            }
            
        try:
            # Map DID to an Ethereum address for the SBT receiver. 
            # In a real system, the DID would resolve to their wallet address.
            # Here we just use a dummy address for demo if mapping fails.
            to_address = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8" # Hardhat Account #1
            
            tx_hash = contract.functions.mintCertification(
                to_address,
                asset_id,
                batch_id,
                evidence_hash
            ).transact({'from': self.account})
            
            receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash)
            
            # The Mint event logs the tokenId. We can parse it or just assume it's next.
            # Let's extract from logs.
            logs = contract.events.CertificationMinted().process_receipt(receipt)
            token_id = logs[0]['args']['tokenId'] if logs else 0
            
            return {
                "tx_hash": receipt.transactionHash.hex(),
                "token_id": token_id,
                "block_number": receipt.blockNumber,
                "gas_used": receipt.gasUsed
            }
        except Exception as e:
            logger.error(f"Minting failed: {e}")
            raise

    def anchor_evidence(self, asset_id: str, evidence_hash: str) -> dict:
        """Anchor evidence hash on-chain by sending a 0 ETH tx with the hash in data."""
        if not self.w3.is_connected() or not self.account:
            return {
                "tx_hash": "0xmock" + evidence_hash[:40],
                "block_number": 2,
                "gas_used": 21000
            }
            
        try:
            # We encode the hash into the transaction data
            data_payload = f"EVIDENCE:{asset_id}:{evidence_hash}".encode('utf-8')
            
            tx = {
                'to': self.account, # Send to self
                'value': 0,
                'data': data_payload,
                'gas': 100000,
                'gasPrice': self.w3.eth.gas_price,
                'nonce': self.w3.eth.get_transaction_count(self.account),
                'chainId': 31337
            }
            
            # Since this is local hardhat node, we can just send_transaction if unlocked
            # or use transact(). Hardhat accounts are unlocked.
            tx_hash = self.w3.eth.send_transaction({'from': self.account, 'to': self.account, 'data': data_payload})
            
            receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash)
            
            return {
                "tx_hash": receipt.transactionHash.hex(),
                "block_number": receipt.blockNumber,
                "gas_used": receipt.gasUsed
            }
        except Exception as e:
            logger.error(f"Anchoring failed: {e}")
            raise

blockchain_service = BlockchainService()
